### ISSUE TITLE
How to embed Navigation View? 

### ISSUE THREAD

**Issue by RamYadlapalli** [SRHealth/react-native-mapbox-navigation#7]
First of all, thanks for this great example, it really helps to get started with mapbox navigation in React Native. 

Right now in the example we are using NavigationLauncher class for the navigation, which by default takes full-screen view to show the navigation. In mapbox navigation SDK examples, there is a way to embed navigation using NavigationView class? 

Is there an example on how to use this in React-Native?

**Comment by richterCLX** [comment]
check out this repo https://github.com/derroobin/react-native-mapbox-navigation
